### ISSUE TITLE
train tracks, straight into a wall

### ISSUE THREAD

**Issue by R0CK3R003** [CitadelCore/remnants-playtest-issues#13]
https://steamuserimages-a.akamaihd.net/ugc/854981112846839187/999AB18AA4632AD8E3BDB3C2BCD273CD28EA032F/

Also, the minitrain stops reversing at this point and the wheels freak out.

**Comment by CitadelCore** [comment]
This is just a placeholder so the map won't leak - it will be removed when the track is completed in 1.0.2.
