### ISSUE TITLE
Possibly another missing Photospot #2

### ISSUE THREAD

**Issue by R0CK3R003** [CitadelCore/remnants-playtest-issues#25]
https://steamuserimages-a.akamaihd.net/ugc/854981112846848713/2418A1DB0B2791E14E9C3571356D57EB4FA8D2AF/

The broken part on the other side of the hallway is a photospot, however this one isn't.
(In #under)

**Comment by CitadelCore** [comment]
Should be fixed. Radius might've been too small.
