### ISSUE TITLE
Fan speed too slow

### ISSUE THREAD

**Issue by R0CK3R003** [CitadelCore/remnants-playtest-issues#28]
https://steamuserimages-a.akamaihd.net/ugc/854981112846850037/895D127B973E78B74528A4D8B1DE1777FEC172BD/

The Fan speed and the generator sound don't match up at all.

**Comment by CitadelCore** [comment]
This is the same speed that the generator fan runs at in the generators in isle2.

**Comment by R0CK3R003** [comment]
Is it possible for you to change it? I mean, most people won't notice it anyways, i'm a bit of a pain there :P

**Comment by CitadelCore** [comment]
No, the animation speed cannot be changed without manual model editing.
