### ISSUE TITLE
Lighting Bug in #house

### ISSUE THREAD

**Issue by R0CK3R003** [CitadelCore/remnants-playtest-issues#5]
https://steamuserimages-a.akamaihd.net/ugc/854981112846837176/925090A887418AB259631050ABE782DF256489E2/

Some sides of the wooden things are not getting lit up, unless the flashlight is used.

**Comment by CitadelCore** [comment]
These wooden posts are being removed in 1.0.1.

**Comment by CitadelCore** [comment]
Removed this entire tunnel.
